@startuml
'https://plantuml.com/class-diagram
class App{
    +main()
    +start()
}
class Item {
    String description
    +int item_id
    +Boolean completion_status
    +Date due_date
    +setDescription():void
}
class User {
    +Int active_list
    +setActiveList():void
    +getActiveList():void
    +addNewTodoList():void
    +removeExistingTodoList():void
    +setTitle():void
    +addItem(String description, Boolean completion_status, Date due_date):void
    +removeItem():void
    +editItemDescription(Item i, String description):void
    +editItemDueDate(Item i, String due_date):void
    +editItemCompletionStatus(Item i, Boolean completion_status):void
    +displayCompleteItems():void
    +displayIncompleteItems():void
    +displayAllItems():void
}
class MainPageController{
    +LoadButtonClicked(ActionEvent actionEvent):void
    +SaveButtonClicked(ActionEvent actionEvent):void
    +RemoveListButtonClicked(ActionEvent actionEvent):void
    +EditListButtonClicked(ActionEvent actionEvent):void
    +AddNewListButtonClicked(ActionEvent actionEvent):void
}
class EditItemPageController{
    +SaveItem(ActionEvent actionEvent):void
    +ReturnToMainPage(ActionEvent actionEvent):void
}
class EditTodoListPageController{
    +EditTodolistItem(ActionEvent actionEvent):void
    +DeleteTodolistItem(ActionEvent actionEvent):void
    +AddTodolistItem(ActionEvent actionEvent):void
    +ReturnToMainPage(ActionEvent actionEvent):void
    +displayAllItems(ActionEvent actionEvent):void
    +displayCompleteItems(ActionEvent actionEvent):void
    +displayIncompleteItems(ActionEvent actionEvent):void
}
javafx.Application <|-- App
javafx.Application <|-- MainPageController
javafx.Application <|-- EditItemPageController
javafx.Application <|-- EditTodoListPageController
MainPageController o-- User
EditItemPageController o-- User
EditTodoListPageController o-- User
Item o-- User
TodoList o-- User
Item *-- TodoList

@enduml